server:
  port: 9999

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#服务器环境：
spring:
  datasource:
    url: jdbc:mysql://43.136.86.199:3306/school_car?zeroDateTimeBehavior=convertToNull
    username: root
    password: WMRzJIs14Kntiur
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

